### ISSUE TITLE
[Question] How to increase the AutoHotkey interface FPS?

### ISSUE THREAD

**Issue by gregoriomartin** [conajer/PoEapi#12]
Hi! First, thanks for this amazing script.

Anyone knowns how to increase the FPS from the interface? Or how to completely disable it? Because when I'm playing the game without autohotkeys it runs at 144fps. When the interface from AHK is started the game's fps drops to 60-70 or even less.

Thanks!

**Comment by conajer** [comment]
Disabling MinimapSymbol would help.
