### ISSUE TITLE
About Tencent

### ISSUE THREAD

**Issue by Aconwy** [conajer/PoEapi#18]
How to use it in Tencent, or can I revise it

**Comment by conajer** [comment]
Sure, you can revise it for yourself.
At first, add PoE exe name in PoE.cpp, then fix the offsets if you are lucky.

**Comment by haosen2006** [comment]
PathOfExile_x64.exe
Can you add this to the latest version? I won't compile. Thank You ！

**Comment by conajer** [comment]
Sorry for late, try poeapi.dll in attachment and good luck.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
