### ISSUE TITLE
Patch 3.19.1c Broke many things 

### ISSUE THREAD

**Issue by SaltedNinja** [conajer/PoEapi#24]
Without giving all the details but the radar is not fully functional please check we need you more than you know :D

**Comment by Xenthalon** [comment]
Will be fixed when conajer merges https://github.com/conajer/PoEapi/pull/25 and releases a new build.

**Comment by SaltedNinja** [comment]
> Will be fixed when conajer merges #25 and releases a new build.

I make the changes you applied in #25 how ever compiling a new poeapi.dll I'm getting error's
`PoEMemory.cpp:122:13: error: reference to 'byte' is ambiguous
  122 |             byte buffer[size];`

**Comment by Xenthalon** [comment]
Had the same issue, you really need to use gcc 10.2 to compile, the current 12.x version gave me the same error.

**Comment by SaltedNinja** [comment]
> Had the same issue, you really need to use gcc 10.2 to compile, the current 12.x version gave me the same error.

After debugging a few hours I have fixed it and works again.

**Comment by sponska** [comment]
oh i need it compiled file
can give file?
