### ISSUE TITLE
Overlay text too small when Windows Desktop scale is larger than 100%

### ISSUE THREAD

**Issue by superarts** [conajer/PoEapi#35]
For example, with 5K monitor I set "Scale" to 200% under System > Display -> Sacle & Layout, and use Windowed Fullscreen in POE with 1080p rendering resolution, to have both sharp text and reasonable performance. `PoEapi` overlay is able to calculate the right position, but the text is only half size as it's supposed to be. It's particularly hard to read in expedition encounter.

I'm seeing some codes in `plugins/MinimapSymbol` like: 

```cpp
                else if (i.id.find(L"Curses") != wstring::npos)
                    poe->draw_text(L"Curses", x, y - 10, 0xffffff, 0x7f0000, 1.0, 1);
```

Would it be possible to get system display scale (it may be a bit tricky, [see here](https://stackoverflow.com/questions/35233182/how-can-i-change-windows-10-display-scaling-programmatically-using-c-sharp)) and use it to multiple the text size in `draw_text` please? Sorry I'm not a windows programmer and lack the knowledge to work on it myself. Thanks!

**Comment by LahkLeKey** [comment]
You can use DPI scaling on windows to fix this or you can edit the css file to support 4k.

I did this a while ago but there were still a few nuances to fix so I abandoned the PR. You will need to fiddle around with it a bit to get it working for your use case.

[ahk/lib/Navi.ahk](https://github.com/conajer/PoEapi/pull/21)

**Comment by superarts** [comment]
Thank you for pointing out the CSS based direction, and hope this project gets updated soon!

Also it would be great to add some other build-breaking expedition remnant affixes, like "overwhelming 100% physical" for melee, and "hit remove 10% energy shield" for CI builds.
