### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by V4mpyr** [conajer/PoEapi#9]
Getting this Syntax error. please advise how to fix. thank you. Starting with admin rights, newest version of AHK I get this error with the master and the normal Poeapikit 1.2.1

Kind regards,

---------------------------
PoEapikit.ahk
---------------------------
Error at line 97 in #include file "C:\Users\Computer\Desktop\PoEapikit-1.2.1\lib\ahkpp.ahk".

Line Text: switch params.Count() {
Error: This line does not contain a recognized action.

The program will exit.
---------------------------
OK   
---------------------------

**Comment by conajer** [comment]
Use the latest AutoHotkey.
